### PR TITLE
SRX IKE lifetime should be 10800s, as route-based?

### PR DESCRIPTION
**Pull request by cbuben**
According to:

https://azure.microsoft.com/en-us/documentation/articles/vpn-gateway-about-vpn-devices/#ipsec-parameters

...route-based VPNs should use IKE SA lifetime of 10800s.

This sample configuration suggests the Azure gateway should use a
route-based configuration, so shouldn't the SRX configuration use 10800s
IKE SA lifetime?

### CODE REVIEW

**Comment by effingerw** [comment]
Resolved with markdown rev thank you for your commit

**Comment by cbuben** [comment]
Hi @effingerw - are you referring to https://github.com/Azure/Azure-vpn-config-samples/commit/8fa7915bd075fc97a109b13123f4a81981b13c85 as the resolution?

If the SRX "show configuration" output is going to continue to be included, shouldn't that be updated too?  Current HEAD on master is still incorrect - https://github.com/Azure/Azure-vpn-config-samples/blob/ae8c34be63d64c9ca9d7f12d60e34830a6bb8816/Juniper/Current/SRX/juniper-srx-junos-12.1_show_configuration.txt#L165

**Comment by effingerw** [comment]
Thanks for the catch I have updated the config file

**Comment by cbuben** [comment]
LGTM, thanks!

**Pull request closed without merging**
